/**
 * \file main-sdl2.c
 * \brief Angband SDL2 port
 *
 * Copyright (c) 1997 Ben Harrison and others
 *
 * This work is free software; you can redistribute it and/or modify it
 * under the terms of either:
 *
 * a) the GNU General Public License as published by the Free Software
 *    Foundation, version 2, or
 *
 * b) the "Angband licence":
 *    This software may be copied and distributed for educational, research,
 *    and not for profit purposes provided that this copyright and statement
 *    are included in all such copies.  Other copyrights may also apply.
 */

#include "angband.h"

#ifdef USE_SDL2

#include "sdl2/pui-ctrl.h"
#include "sdl2/pui-dlg.h"
#include "sdl2/pui-misc.h"
#include "sdl2/pui-win.h"
#include "SDL_image.h"
#ifdef SOUND_SDL2
#include "SDL_mixer.h"
#endif
#include "SDL_revision.h"

#include "main.h"
#include "init.h"
#include "ui-term.h"
#include "buildid.h"
#include "ui-display.h"
#include "ui-command.h"
#include "player-calcs.h"
#include "ui-output.h"
#include "game-world.h"
#include "ui-input.h"
#include "ui-prefs.h"
#include "grafmode.h"
#include "ui-game.h"
#include "ui-map.h"
#include "parser.h"
#ifdef SOUND_SDL2
#include "sound.h"
#endif

/* Forward declarations for companion UI */
extern errr companion_init(struct subwindow *subwindow);
extern void companion_free(struct companion_data *companion);
extern void render_companion_window(struct subwindow *subwindow);

#define MAX_SUBWINDOWS \
	ANGBAND_TERM_MAX
/* that should be plenty... */
#define MAX_WINDOWS 4

#define INIT_SDL_FLAGS \
	(SDL_INIT_VIDEO | SDL_INIT_GAMECONTROLLER)
#define INIT_IMG_FLAGS \
	(IMG_INIT_PNG)

/* this is the main term screen, where all the action takes place */
#define MAIN_SUBWINDOW 0
/* for symmetry with main subwindow */
#define MAIN_WINDOW 0
/* size of the keypress queue (term->key_queue) */
#define SUBWINDOW_KEYQ_SIZE(subwindow_ptr) \
	((subwindow_ptr)->index == MAIN_SUBWINDOW ? 1024 : 32)

#define DEFAULT_DISPLAY 0

#define DEFAULT_CONFIG_FILE "sdl2init.txt"
#define DEFAULT_CONFIG_FILE_DIR \
	ANGBAND_DIR_USER

#define DEFAULT_ALPHA_FULL 0xFF
#define ALPHA_PERCENT(p) \
	(DEFAULT_ALPHA_FULL * (p) / 100)
#define DEFAULT_ALPHA_LOW \
	ALPHA_PERCENT(80)
/* for "Alpha" button; in percents */
#define DEFAULT_ALPHA_STEP 10
#define DEFAULT_ALPHA_LOWEST 0

#define DEFAULT_WALLPAPER "att-128.png"
#define DEFAULT_WALLPAPER_DIR \
	ANGBAND_DIR_ICONS
#define DEFAULT_WINDOW_ICON "att-32.png"
#define DEFAULT_WINDOW_ICON_DIR \
	ANGBAND_DIR_ICONS
#define DEFAULT_ABOUT_ICON "att-128.png"
#define DEFAULT_ABOUT_ICON_DIR \
	ANGBAND_DIR_ICONS

#define DEFAULT_FONT_HINTING \
	TTF_HINTING_LIGHT
/* border of subwindows, in pixels */
#define DEFAULT_BORDER 8
#define DEFAULT_XTRA_BORDER \
	(DEFAULT_BORDER * 2)
#define DEFAULT_VISIBLE_BORDER 2

/* XXX hack: the widest character present in a font
 * for determining font advance (width) */
#define GLYPH_FOR_ADVANCE 'W'
#define DEFAULT_VECTOR_FONT_SIZE 12

#define DEFAULT_FONT "10x20x.fon"

#define DEFAULT_DIALOG_FONT "8x13x.fon"

#define MAX_VECTOR_FONT_SIZE 64
#define MIN_VECTOR_FONT_SIZE 4

/* update period in window delays (160 milliseconds, assuming 60 fps) */
#define DEFAULT_IDLE_UPDATE_PERIOD 10

#define DEFAULT_WINDOW_BG_COLOR \
	COLOUR_L_DARK
#define DEFAULT_SUBWINDOW_BG_COLOR \
	COLOUR_DARK
#define DEFAULT_SUBWINDOW_CURSOR_COLOR \
	COLOUR_YELLOW
#define DEFAULT_SHADE_COLOR \
	COLOUR_SHADE
#define DEFAULT_SUBWINDOW_BORDER_COLOR \
	COLOUR_SHADE

#define DEFAULT_ERROR_COLOR \
	COLOUR_RED

/* shockbolt's tiles are 64x64; dungeon is 198 tiles long;
 * 64 * 198 is 12672 which is bigger than any possible texture! */
#define REASONABLE_MAP_TILE_WIDTH 16
#define REASONABLE_MAP_TILE_HEIGHT 16

/* angband needs at least 80x24 main term, else severe bugs happen */
#define MIN_COLS_MAIN 80
#define MIN_ROWS_MAIN 24
/* some reasonable values - we dont want the player to resize
 * the term into nothing! */
#define MIN_COLS_OTHER 12
#define MIN_ROWS_OTHER 3

#define MIN_TILE_WIDTH 1
#define MAX_TILE_WIDTH 9
#define MIN_TILE_HEIGHT 1
#define MAX_TILE_HEIGHT 9

#define DEFAULT_SNAP_RANGE(window) (window->app->def_font_w)

enum wallpaper_mode {
	/* so that we won't forget to actually set wallpaper */
	WALLPAPER_INVALID = 0,
	WALLPAPER_DONT_SHOW,
	WALLPAPER_TILED,
	WALLPAPER_CENTERED,
	WALLPAPER_SCALED
};

enum font_type {
	FONT_TYPE_INVALID = 0,
	FONT_TYPE_RASTER,
	FONT_TYPE_VECTOR
};

struct ttf {
	TTF_Font *handle;
	struct { int w; int h; } glyph;
};

/* the array of ascii chars was generated by this perl script:
 * my $ascii = join '', map /\p{Print}/ ? $_ : ' ', map chr, 0 .. 127; 
 * for (my $i = 0; $i < length($ascii); $i += 32) {
 *     my $s = substr $ascii, $i, 32;
 *     $s =~ s#\\#\\\\#g;
 *     $s =~ s#"#\\"#g;
 *     print qq(\t"$s"\n);
 * }
 * and then manually hacked to substitute the escape codes for the non-null
 * control characters (0x01 to 0x1f, and 0x7f) so the graphics characters at
 * those indices in Angband's packaged .fon files remain available, if the
 * user wants to access them (those characters are likely the ones specified by
 * code page 437, https://en.wikipedia.org/wiki/Code_page_437 ).
 */
static const char g_ascii_codepoints_for_cache[] =
	" \x01\x02\x03\x04\x05\x06\x07\x08\x09\x0a\x0b\x0c\x0d\x0e\x0f"
	"\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f"
	" !\"#$%&'()*+,-./0123456789:;<=>?"
	"@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_"
	"`abcdefghijklmnopqrstuvwxyz{|}~\x7f";
/* Simple font cache. Only for ascii (which is like 99.99% (?) of what the game
 * displays, anyway) */
#define ASCII_CACHE_SIZE \
		(N_ELEMENTS(g_ascii_codepoints_for_cache) - 1)
struct font_cache {
	SDL_Texture *texture;
	/* it wastes some space... so what? */
	SDL_Rect rects[ASCII_CACHE_SIZE];
};
/* 0 is also a valid codepoint, of course... that's just for finding bugs */
#define IS_CACHED_ASCII_CODEPOINT(c) \
		((c) > 0 && (c) < ASCII_CACHE_SIZE)

struct font {
	struct ttf ttf;
	char *name;
	char *path;
	int size;
	/* index of font in the application's fonts array */
	size_t index;

	struct font_cache cache;
};

struct subwindow_border {
	bool visible;
	bool error;
	SDL_Color color;
	int width;
};

struct subwindow_config {
	char *font_name;
	int font_size;
};

struct window_config {
	int renderer_flags;
	int renderer_index;
	int window_flags;

	char *wallpaper_path;
	char *font_name;
	int font_size;
};

/* struct subwindow is representation of angband's term */
struct subwindow {
	bool inited;
	bool loaded;
	bool linked;
	bool visible;

	struct subwindow_config *config;

	/* top in z-order */
	bool top;
	bool always_top;

	unsigned index;

	int rows;
	int cols;

	/* struct ttf also has this information; these members are
	 * just for convenience */
	int font_width;
	int font_height;

	/*
	 * These are transiently used during font selection for the subwindow.
	 * The font size must be >= min_font_size and < max_font_size to
	 * match the constraints of the subwindow's miniumum number of columns
	 * and rows and the size of the window containing the subwindow.
	 */
	int min_font_size, max_font_size;

	/* coordinates of full rect are relative to coordinates of window
	 * (basically, full rect is texture) */
	SDL_Rect full_rect;
	/* coordinates of inner rect are relative to that of full rect */
	SDL_Rect inner_rect;
	/* for use when resizing term */
	SDL_Rect sizing_rect;
	/* version of full_rect for the opposite setting of fullscreen */
	SDL_Rect stored_rect;
	/* a one pixel texture, mostly for displaying something when
	 * the player is resizing term */
	SDL_Texture *aux_texture;

	/* background color */
	SDL_Color color;

	struct subwindow_border borders;

	SDL_Texture *texture;

	struct font *font;

	struct sdlpui_window *window;
	struct term *term;
	struct my_app *app;
	
	/* Companion data for MCP AI companion */
	struct companion_data *companion;
};

struct graphics {
	SDL_Texture *texture;
	int id;
	int tile_pixel_w;
	int tile_pixel_h;

	int overdraw_row;
	int overdraw_max;
};

/* thats for dragging terms */
struct move_state {
	bool active;
	bool moving;

	int originx;
	int originy;

	struct subwindow *subwindow;
};

/* thats for resizing terms */
struct size_state {
	bool active;
	bool sizing;

	int originx;
	int originy;

	bool left;
	bool top;

	struct subwindow *subwindow;
};

struct wallpaper {
	int w;
	int h;
	SDL_Texture *texture;
	enum wallpaper_mode mode;
};

/* struct sdlpui_window is a real window on screen, it has one or more
 * subwindows (terms) in it */
struct sdlpui_window {
	bool inited;
	bool loaded;

	/* id is SDL's id, for use with events */
	Uint32 id;
	/* and this is our id, mostly for debugging */
	unsigned index;
	/* index of transiently outlined subwindow */
	unsigned outlined_subwindow;

	struct window_config *config;

	/* window has changed and must be redrawn */
	bool dirty;

	/* limiter for frames */
	Uint32 next_redraw;
	/* from display mode */
	int delay;

	/* as reported by SDL_GetWindowFlags() */
	Uint32 flags;

	/* position and size of window as it is on display */
	SDL_Rect full_rect;
	/* size of window without status bar, basically */
	SDL_Rect inner_rect;
	/* version of full_rect for the opposite setting of fullscreen */
	SDL_Rect stored_rect;

	SDL_Color color;
	/* for making terms transparent while moving or sizing them */
	Uint8 alpha;

	SDL_Window *window;
	SDL_Renderer *renderer;
	/* The font to use for this window's dialogs and menus */
	struct font *dialog_font;
	/* The status bar (i.e. menu bar) for the window */
	struct sdlpui_dialog *status_bar;
	/* The buttons in the status bar for moving and resizing the window */
	struct sdlpui_control *move_button;
	struct sdlpui_control *size_button;
	/* The about dialog; NULL if not currently displayed */
	struct sdlpui_dialog *infod;
	/* The keyboard shortcut dialog; NULL if not currently displayed */
	struct sdlpui_dialog *shorte;
	/* The SDL details dialog; NULL if not currently displayed */
	struct sdlpui_dialog *detaild;

	int pixelformat;

	struct wallpaper wallpaper;
	struct sdlpui_stipple stipple;
	struct move_state move_state;
	struct size_state size_state;
	struct graphics graphics;

	struct subwindow *subwindows[MAX_SUBWINDOWS];

	/* Point back to the containing application */
	struct my_app *app;

	/*
	 * These are the head and tail of the stack of menus/dialogs for this
	 * window.  Both will be NULL if no menus/dialogs are active.
	 */
	struct sdlpui_dialog *d_head, *d_tail;

	/*
	 * These point to the dialog/menu that should receive mouse events or
	 * keyboard events, respectively.  If NULL, events will be directed
	 * to the game's core.
	 */
	struct sdlpui_dialog *d_mouse, *d_key;
};

struct font_info {
	char *name;
	char *path;
	int size;
	size_t index;
	enum font_type type;
};

struct shortcut_editor_data {
	struct sdlpui_control labels[MAX_WINDOWS];
	struct sdlpui_control shortcut_displays[MAX_WINDOWS];
	struct sdlpui_control change_buttons[MAX_WINDOWS];
	struct sdlpui_control clear_buttons[MAX_WINDOWS];
	struct sdlpui_control prompt_label;
	struct sdlpui_control close_button;
	struct sdlpui_control reset_button;
	int changing_shortcut;
};

struct my_app {
	/*
	 * The string ANGBAND_DIR_USER is freed before calling quit_hook(),
	 * so we need to save the path to the config file.
	 */
	char config_file[4096];
	/* the game's color table translated into what SDL expects */
	SDL_Color colors[MAX_COLORS];
	/*
	 * fonts from the game's lib/fonts directory that can be selected
	 * directly from the menus
	 */
	struct font_info *fonts;
	struct subwindow subwindows[MAX_SUBWINDOWS];
	struct sdlpui_window windows[MAX_WINDOWS];
	struct keypress menu_shortcuts[MAX_WINDOWS];
	/*
	 * point to the window that should receive mouse and key events,
	 * respectively
	 */
	struct sdlpui_window *w_mouse;
	struct sdlpui_window *w_key;
	/* Number of entries stored in fonts */
	int font_count;
	/* Number of entries allocated in fonts */
	int font_alloc;
	/* Width and height on screen for the default font */
	int def_font_w, def_font_h;
	/*
	 * true if KC_MOD_KEYPAD will be sent for numeric keypad keys at the
	 * expense of not handling some keyboard layouts properly
	 */
	bool kp_as_mod;
	/* true if details about the SDL environment are to be logged. */
	bool print_sdl_details;

	SDL_GameController *controller;
};

/* Forward declarations */

static void init_globals(struct my_app *a);
static void free_globals(struct my_app *a);
static bool read_config_file(struct my_app *a);
static void dump_config_file(const struct my_app *a);
static void init_colors(struct my_app *a);
static void start_windows(struct my_app *a);
static void start_window(struct sdlpui_window *window);
static void load_font(struct font *font);
static bool reload_font(struct subwindow *subwindow,
		const struct font_info *info);
static void free_font(struct font *font);
static const struct font_info *find_font_info(const struct font_info *fonts,
		int nfonts, const char *name);
static struct font *make_font(const struct sdlpui_window *window,
		const char *name, int size);
static struct sdlpui_window *get_new_window(struct my_app *a, unsigned index);
static void wipe_window(struct sdlpui_window *window, int display);
/* create default config for spawning a window via gui */
static void wipe_window_aux_config(struct sdlpui_window *window);
static void adjust_window_geometry(struct sdlpui_window *window);
static void free_window(struct sdlpui_window *window);
static struct sdlpui_window *get_window_by_id(struct my_app *a, Uint32 id);
static struct sdlpui_window *get_window_direct(struct my_app *a,
		unsigned index);
static void resize_window(struct sdlpui_window *window, int w, int h);
static void resize_subwindow(struct subwindow *subwindow);
static struct subwindow *get_new_subwindow(struct my_app *a, unsigned index);
static void load_subwindow(struct sdlpui_window *window,
		struct subwindow *subwindow);
static bool is_subwindow_loaded(struct my_app *a, unsigned index);
static struct subwindow *transfer_subwindow(struct sdlpui_window *window,
		unsigned index);
static struct subwindow *get_subwindow_by_xy(const struct sdlpui_window *window,
		int x, int y);
static struct subwindow *get_subwindow_by_index(
		const struct sdlpui_window *window, unsigned index,
		bool visible);
static struct subwindow *get_subwindow_direct(struct my_app *a, unsigned index);
/* this function loads new subwindow if it's not already loaded */
static struct subwindow *make_subwindow(struct sdlpui_window *window,
		unsigned index);
static void sort_to_top(struct sdlpui_window *window);
static void bring_to_top(struct sdlpui_window *window,
		struct subwindow *subwindow);
static void render_borders(struct subwindow *subwindow);
static SDL_Texture *load_image(const struct sdlpui_window *window,
		const char *path);
static void reload_all_graphics(struct my_app *a, graphics_mode *mode);
static void free_graphics(struct graphics *graphics);
static void load_terms(struct my_app *a);
static void load_term(struct subwindow *subwindow);
static void clear_pw_flag(struct subwindow *subwindow);
static bool adjust_subwindow_geometry(const struct sdlpui_window *window,
		struct subwindow *subwindow);
static bool is_ok_col_row(const struct subwindow *subwindow,
		const SDL_Rect *rect, int cell_w, int cell_h);
static void resize_rect(SDL_Rect *rect,
		int left, int top, int right, int bottom);
static void crop_rects(SDL_Rect *src, SDL_Rect *dst);
static bool is_point_in_rect(int x, int y, const SDL_Rect *rect);
static bool is_close_to(int a, int b, unsigned range);
static void handle_window_closed(struct my_app *a,
		struct sdlpui_window *window);
static void refresh_angband_terms(struct my_app *a);
static void handle_quit(void);
static void wait_anykey(struct my_app *a);
static void keyboard_event_to_angband_key(const SDL_KeyboardEvent *key,
		bool kp_as_mod, keycode_t *ch, uint8_t *mods);
static void textinput_event_to_angband_key(const SDL_TextInputEvent *key,
		bool kp_as_mod, keycode_t *ch, uint8_t *mods);
static void recreate_textures(struct my_app *a, bool all);

/* Global variables. */

const char help_sdl2[] = "SDL2 frontend, subopts -v";
static struct my_app g_app;
static Uint32 SHORTCUT_EDITOR_CODE;

/*
 * Provide the hooks needed by primitive UI toolkit for SDL2.
 */
SDL_Renderer *sdlpui_get_renderer(struct sdlpui_window *w)
{
	return w->renderer;
}

TTF_Font *sdlpui_get_ttf(struct sdlpui_window *w)
{
	assert(w->dialog_font && w->dialog_font->ttf.handle);
	return w->dialog_font->ttf.handle;
}

struct sdlpui_stipple *sdlpui_get_stipple(struct sdlpui_window *w)
{
	return &w->stipple;
}

const SDL_Color *sdlpui_get_color(struct sdlpui_window *w, int role)
{
	int idx;

	switch (role) {
	case SDLPUI_COLOR_MENU_BG:
	case SDLPUI_COLOR_COUNTERSINK:
		idx = COLOUR_DARK;
		break;

	case SDLPUI_COLOR_MENU_FG:
	case SDLPUI_COLOR_DIALOG_FG:
	case SDLPUI_COLOR_DIALOG_BORDER:
		idx = COLOUR_WHITE;
		break;

	case SDLPUI_COLOR_MENU_BORDER:
	case SDLPUI_COLOR_DIALOG_BG:
		idx = COLOUR_SHADE;
		break;

	default:
		/*
		 * Should not happen; assign a safe index in case assertions
		 * are optimized away.
		 */
		SDL_assert(0);
		idx = 0;
		break;
	}

	SDL_assert(idx >= 0 && idx < MAX_COLORS);
	return &w->app->colors[idx];
}

void sdlpui_signal_redraw(struct sdlpui_window *w)
{
	w->dirty = true;
}

void sdlpui_dialog_push_to_top(struct sdlpui_window *w, struct sdlpui_dialog *d)
{
	bool redraw = true;

	/* Unlink. */
	if (d->next) {
		d->next->prev = d->prev;
	} else if (w->d_tail == d) {
		w->d_tail = d->prev;
	}
	if (d->prev) {
		d->prev->next = d->next;
	} else if (w->d_head == d) {
		redraw = false;
		w->d_head = d->next;
	}

	/* Put at the top. */
	d->prev = NULL;
	d->next = w->d_head;
	if (d->next) {
		d->next->prev = d;
	} else {
		SDL_assert(!w->d_tail);
		w->d_tail = d;
	}
	w->d_head = d;

	if (redraw) {
		sdlpui_signal_redraw(w);
	}
}

void sdlpui_dialog_pop(struct sdlpui_window *w, struct sdlpui_dialog *d)
{
	if (w->d_mouse == d) {
		w->d_mouse = NULL;
	}
	if (w->d_key == d) {
		w->d_key = NULL;
	}
	if (d->next) {
		d->next->prev = d->prev;
	} else {
		SDL_assert(w->d_tail == d);
		w->d_tail = d->prev;
	}
	if (d->prev) {
		d->prev->next = d->next;
	} else {
		SDL_assert(w->d_head == d);
		w->d_head = d->next;
	}
	w->dirty = true;
}

void sdlpui_dialog_gain_key_focus(struct sdlpui_window *w,
		struct sdlpui_dialog *d)
{
	w->d_key = d;
}

void sdlpui_dialog_yield_key_focus(struct sdlpui_window *w,
		struct sdlpui_dialog *d)
{
	if (w->d_key == d) {
		w->d_key = NULL;
	}
}

void sdlpui_dialog_gain_mouse_focus(struct sdlpui_window *w,
		struct sdlpui_dialog *d)
{
	w->d_mouse = d;
}

void sdlpui_dialog_yield_mouse_focus(struct sdlpui_window *w,
		struct sdlpui_dialog *d)
{
	if (w->d_mouse == d) {
		w->d_mouse = NULL;
	}
}

struct sdlpui_dialog *sdlpui_dialog_with_key_focus(struct sdlpui_window *w)
{
	return w->d_key;
}

struct sdlpui_dialog *sdlpui_dialog_with_mouse_focus(struct sdlpui_window *w)
{
	return w->d_mouse;
}

void sdlpui_force_quit(void)
{
	quit("sdlpui failure");
}

/* Functions */

static void log_window_details(int my_index, SDL_Window *w, SDL_Renderer *r)
{
	Uint32 flags = SDL_GetWindowFlags(w);
	int wid, hgt, x, y, bt, bl, bb, br;
	SDL_RendererInfo r_info;

	SDL_Log("Window %d:", my_index);
	SDL_Log("    Display index and ID: %d %lu",
		SDL_GetWindowDisplayIndex(w),
		(unsigned long)SDL_GetWindowID(w));
	SDL_GetWindowPosition(w, &x, &y);
	SDL_GetWindowSize(w, &wid, &hgt);
	SDL_Log("    Geometry: (%d, %d) %d x %d", x, y, wid, hgt);
	SDL_GetWindowBordersSize(w, &bt, &bl, &bb, &br);
	SDL_Log("    Border sizes: %d %d %d %d", bt, bl, bb, br);
	/* Skipping the more transient flags about focus and grabs. */
	SDL_Log("    Flags:%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s",
		(flags & SDL_WINDOW_FULLSCREEN) ? " FULLSCREEN" : "",
		(flags & SDL_WINDOW_OPENGL) ? " OPENGL" : "",
		(flags & SDL_WINDOW_SHOWN) ? " SHOWN" : "",
		(flags & SDL_WINDOW_HIDDEN) ? " HIDDEN" : "",
		(flags & SDL_WINDOW_BORDERLESS) ? " BORDERLESS" : "",
		(flags & SDL_WINDOW_RESIZABLE) ? " RESIZABLE" : "",
		(flags & SDL_WINDOW_MINIMIZED) ? " MINIMIZED" : "",
		(flags & SDL_WINDOW_MAXIMIZED) ? " MAXIMIZED" : "",
		(flags & SDL_WINDOW_FULLSCREEN_DESKTOP)
		? " FULLSCREEN_DESKTOP" : "",
		(flags & SDL_WINDOW_FOREIGN) ? " FOREIGN" : "",
		(flags & SDL_WINDOW_ALLOW_HIGHDPI) ? " ALLOW_HIGHDPI" : "",
		(flags & SDL_WINDOW_ALWAYS_ON_TOP) ? " ALWAYS_ON_TOP" : "",
		(flags & SDL_WINDOW_SKIP_TASKBAR) ? " SKIP_TASKBAR" : "",
		(flags & SDL_WINDOW_UTILITY) ? " UTILITY" : "",
		(flags & SDL_WINDOW_POPUP_MENU) ? " POPUP_MENU" : "",
		(flags & SDL_WINDOW_VULKAN) ? " VULKAN" : "",
		(flags & SDL_WINDOW_METAL) ? " METAL" : "");

	if (!r) return;
	if (SDL_GetRendererInfo(r, &r_info)) {
		SDL_Log("    Renderer: No details available: %s",
			SDL_GetError());
	} else {
		SDL_Log("    Renderer: %s", r_info.name);
		if (SDL_GetRendererOutputSize(r, &wid, &hgt)) {
			SDL_Log("        Output size: %s", SDL_GetError());
		} else {
			SDL_Log("        Output size: %d x %d", wid, hgt);
		}
		SDL_Log("        Maximum texture size: %d x %d",
			r_info.max_texture_width, r_info.max_texture_height);
		SDL_Log("        Flags:%s%s%s%s",
			(r_info.flags & SDL_RENDERER_SOFTWARE)
			? " SOFTWARE" : "",
			(r_info.flags & SDL_RENDERER_ACCELERATED)
			? " ACCELERATED" : "",
			(r_info.flags & SDL_RENDERER_PRESENTVSYNC)
			? " PRESENTVSYNC" : "",
			(r_info.flags & SDL_RENDERER_TARGETTEXTURE)
			? " TARGETTEXTURE" : "");
	}
}

static void render_clear(const struct sdlpui_window *window,
		SDL_Texture *texture, const SDL_Color *color)
{
	SDL_SetRenderTarget(window->renderer, texture);
	SDL_SetRenderDrawColor(window->renderer,
			color->r, color->g, color->b, color->a);
	SDL_RenderClear(window->renderer);
}

static void render_wallpaper_tiled(const struct sdlpui_window *window)
{
	SDL_SetRenderTarget(window->renderer, NULL);

	SDL_Rect rect = {0, 0, window->wallpaper.w, window->wallpaper.h};
	for (rect.y = window->inner_rect.y;
			rect.y < window->inner_rect.h;
			rect.y += rect.h)
	{
		for (rect.x = window->inner_rect.x;
				rect.x < window->inner_rect.w;
				rect.x += rect.w)
		{
			SDL_RenderCopy(window->renderer, window->wallpaper.texture, NULL, &rect);
		}
	}
}

static void render_wallpaper_scaled(const struct sdlpui_window *window)
{
	SDL_SetRenderTarget(window->renderer, NULL);
	SDL_RenderCopy(window->renderer, window->wallpaper.texture, NULL, NULL);
}

static void render_wallpaper_centered(const struct sdlpui_window *window)
{
	SDL_Rect rect;

	rect.w = window->wallpaper.w;
	rect.h = window->wallpaper.h;
	rect.x = window->inner_rect.x + (window->inner_rect.w - rect.w) / 2;
	rect.y = window->inner_rect.y + (window->inner_rect.h - rect.h) / 2;

	SDL_SetRenderTarget(window->renderer, NULL);
	SDL_RenderCopy(window->renderer, window->wallpaper.texture, NULL, &rect);
}

static void render_background(const struct sdlpui_window *window)
{
	render_clear(window, NULL, &window->color);

	switch (window->wallpaper.mode) {
		case WALLPAPER_DONT_SHOW:
			return;
		case WALLPAPER_TILED:
			render_wallpaper_tiled(window);
			return;
		case WALLPAPER_CENTERED:
			render_wallpaper_centered(window);
			return;
		case WALLPAPER_SCALED:
			render_wallpaper_scaled(window);
			return;
		default:
			quit_fmt("bad wallpaper mode %d in window %u",
					window->wallpaper.mode, window->index);
			break;
	}
}

static void render_outline_rect(const struct sdlpui_window *window,
		SDL_Texture *texture, const SDL_Rect *rect, const SDL_Color *color)
{
	SDL_SetRenderTarget(window->renderer, texture);
	SDL_SetRenderDrawColor(window->renderer,
			color->r, color->g, color->b, color->a);
	SDL_RenderDrawRect(window->renderer, rect);
}

static void render_outline_rect_width(const struct sdlpui_window *window,
		SDL_Texture *texture, const SDL_Rect *rect, const SDL_Color *color, int width)
{
	SDL_Rect dst = *rect;

	for (int i = 0; i < width; i++) {
		render_outline_rect(window, texture, &dst, color);
		resize_rect(&dst, 1, 1, -1, -1);
	}
}

static void render_fill_rect(const struct sdlpui_window *window,
		SDL_Texture *texture, const SDL_Rect *rect, const SDL_Color *color)
{
	SDL_SetRenderTarget(window->renderer, texture);
	SDL_SetRenderDrawColor(window->renderer,
			color->r, color->g, color->b, color->a);
	SDL_RenderFillRect(window->renderer, rect);
}

static void render_all(struct sdlpui_window *window)
{
	size_t i;
	struct sdlpui_dialog *d;

	render_background(window);

	for (d = window->d_tail; d; d = d->prev) {
		if (d->texture) {
			SDL_RenderCopy(window->renderer, d->texture, NULL,
				&d->rect);
		} else if (d->ftb->render) {
			(*d->ftb->render)(d, window);
		}
	}

	for (i = 0; i < N_ELEMENTS(window->subwindows); i++) {
		struct subwindow *subwindow = window->subwindows[i];

		if (subwindow != NULL && subwindow->visible) {
			/* Check if this is a companion window */
			if (subwindow->term->sidebar_mode & PW_COMPANION && subwindow->companion) {
				render_companion_window(subwindow);
				continue;
			}
			
			SDL_RenderCopy(window->renderer,
					subwindow->texture,
					NULL, &subwindow->full_rect);
		}
	}
}

static void render_status_bar(struct sdlpui_window *window)
{
	struct sdlpui_dialog *d;

	for (d = window->d_tail; d; d = d->prev) {
		if (d->dirty) {
			if (d->ftb->render) {
				(*d->ftb->render)(d, window);
			}
			if (d->texture) {
				SDL_RenderCopy(window->renderer, d->texture,
					NULL, &d->rect);
			}
		} else if (d->texture) {
			SDL_RenderCopy(window->renderer, d->texture, NULL,
				&d->rect);
		} else if (d->ftb->render) {
			(*d->ftb->render)(d, window);
		}
	}
}

static void render_window_while_menu_active(struct sdlpui_window *window)
{
	size_t i;
	struct sdlpui_dialog *d;

	render_background(window);

	SDL_SetRenderTarget(window->renderer, NULL);

	for (i = 0; i < N_ELEMENTS(window->subwindows); i++) {
		struct subwindow *subwindow = window->subwindows[i];
		if (subwindow != NULL && subwindow->visible) {
			if (subwindow->sizing_rect.w > 0 && subwindow->sizing_rect.h > 0) {
				SDL_SetRenderTarget(window->renderer, subwindow->aux_texture);
				/* in case subwindow's color changed */
				render_fill_rect(window,
						subwindow->aux_texture, NULL, &subwindow->color);

				SDL_SetRenderTarget(window->renderer, NULL);
				SDL_RenderCopy(window->renderer,
						subwindow->aux_texture, NULL, &subwindow->sizing_rect);
			}

			SDL_RenderCopy(window->renderer,
					subwindow->texture,
					NULL, &subwindow->full_rect);
			if (subwindow->index == window->outlined_subwindow) {
				int outline_width = (subwindow->full_rect.w
					- subwindow->inner_rect.w) / 2
					- subwindow->borders.width;
				SDL_Rect outline_rect = subwindow->full_rect;

				resize_rect(&outline_rect,
					subwindow->borders.width,
					subwindow->borders.width,
					-subwindow->borders.width,
					-subwindow->borders.width);
				render_outline_rect_width(window, NULL,
					&outline_rect,
					&subwindow->app->colors[DEFAULT_SUBWINDOW_BORDER_COLOR],
					outline_width);
			}
		}
	}

	/*
	 * Render any dialogs or menus last, back to front, so they can draw
	 * over subwindows.
	 */
	for (d = window->d_tail; d; d = d->prev) {
		if (d->ftb->render && (d->dirty || !d->texture)) {
			(*d->ftb->render)(d, window);
		}
		d->dirty = false;
		if (d->texture) {
			SDL_SetRenderTarget(window->renderer, NULL);
			SDL_RenderCopy(window->renderer, d->texture, NULL,
				&d->rect);
		}
	}
}

static void set_subwindow_alpha(struct subwindow *subwindow, int alpha)
{
	SDL_SetTextureAlphaMod(subwindow->texture, alpha);
	SDL_SetTextureAlphaMod(subwindow->aux_texture, alpha);
}

static void set_subwindows_alpha(const struct sdlpui_window *window, int alpha)
{
	for (size_t i = 0; i < N_ELEMENTS(window->subwindows); i++) {
		struct subwindow *subwindow = window->subwindows[i];
		if (subwindow != NULL) {
			set_subwindow_alpha(subwindow, alpha);
		}
	}
}

/* this function allows to perform special things that are not
 * needed while playing the game, like moving terms */
static void redraw_window_while_menu_active(struct sdlpui_window *window)
{
	set_subwindows_alpha(window, window->alpha);
	render_window_while_menu_active(window);
	SDL_RenderPresent(window->renderer);
	window->next_redraw = SDL_GetTicks() + window->delay;
}

/* this function is mostly used while normally playing the game */
static void redraw_window(struct sdlpui_window *window)
{
	if (window->move_state.moving || window->size_state.sizing
			|| window->d_mouse || window->d_key) {
		redraw_window_while_menu_active(window);
		return;
	}

	render_all(window);
	SDL_RenderPresent(window->renderer);
	window->next_redraw = SDL_GetTicks() + window->delay;
}

static void try_redraw_window(struct sdlpui_window *window)
{
	if (window->next_redraw < SDL_GetTicks()) {
		redraw_window(window);
	}
}

static void redraw_all_windows(struct my_app *a, bool dirty)
{
	for (unsigned i = 0; i < MAX_WINDOWS; i++) {
		struct sdlpui_window *window = get_window_direct(a, i);
		if (window != NULL && (dirty ? window->dirty : true)) {
			render_status_bar(window);
			redraw_window(window);
			window->dirty = false;
		}
	}
}

/* this function is typically called in a loop, so for efficiency it doesn't
 * SetRenderTarget; caller must do it (but it does SetTextureColorMod) */
static void render_glyph_mono(const struct sdlpui_window *window,
		const struct font *font, SDL_Texture *dst_texture,
		int x, int y, const SDL_Color *fg, uint32_t codepoint)
{
	if (codepoint == ' ') {
		return;
	}

	SDL_Rect dst = {x, y, font->ttf.glyph.w, font->ttf.glyph.h};

	if (IS_CACHED_ASCII_CODEPOINT(codepoint)) {
		SDL_Rect src = font->cache.rects[codepoint];

		crop_rects(&src, &dst);

		SDL_SetTextureColorMod(font->cache.texture, fg->r, fg->g, fg->b);

		SDL_RenderCopy(window->renderer,
				font->cache.texture, &font->cache.rects[codepoint], &dst);
	} else {
		SDL_Surface *surface = TTF_RenderGlyph_Blended(font->ttf.handle,
				(Uint16) codepoint, *fg);
		if (surface == NULL) {
			return;
		}

		SDL_Texture *texture = SDL_CreateTextureFromSurface(window->renderer, surface);
		assert(texture != NULL);

		SDL_Rect src = {0, 0, surface->w, surface->h};

		crop_rects(&src, &dst);

		SDL_RenderCopy(window->renderer, texture, &src, &dst);

		SDL_FreeSurface(surface);
		SDL_DestroyTexture(texture);
	}
}

static void render_cursor(struct subwindow *subwindow, 
		int col, int row, bool big)
{
	SDL_Color color = subwindow->app->colors[DEFAULT_SUBWINDOW_CURSOR_COLOR];
	SDL_Rect rect = {
		subwindow->inner_rect.x + subwindow->font_width * col,
		subwindow->inner_rect.y + subwindow->font_height * row,
		subwindow->font_width * (big ? tile_width : 1),
		subwindow->font_height * (big ? tile_height : 1)
	};

	render_outline_rect(subwindow->window, subwindow->texture,
			&rect, &color);
}

static void render_grid_cell_text(const struct subwindow *subwindow,
		SDL_Texture *texture, int x, int y)
{
	struct grid_data grid_data;
	int a;
	int ta;
	wchar_t c;
	wchar_t tc;

	map_info(loc(x, y), &grid_data);
	grid_data_as_text(&grid_data, &a, &c, &ta, &tc);
	/* apparently either the same as a or obscured by a */
	(void) tc;

	SDL_Color fg = subwindow->app->colors[a % MAX_COLORS];
	SDL_Color bg;

	switch (ta / MULT_BG) {
		case BG_BLACK:
			bg = subwindow->color;
			break;
		case BG_SAME:
			bg = fg;
			break;
		case BG_DARK:
			bg = subwindow->app->colors[DEFAULT_SHADE_COLOR];
			break;
		default:
			/* debugging */
			bg = subwindow->app->colors[DEFAULT_ERROR_COLOR];
	}

	SDL_Rect rect = {
		x * subwindow->font_width,
		y * subwindow->font_height,
		subwindow->font_width,
		subwindow->font_height
	};

	render_fill_rect(subwindow->window, texture, &rect, &bg);
	render_glyph_mono(subwindow->window,
			subwindow->font, texture, rect.x, rect.y, &fg, (uint32_t) c);
}

/* does not SetRenderTarget */
static void render_tile_rect_scaled(const struct subwindow *subwindow,
		int col, int row, SDL_Rect dst, int a, int c)
{
	struct graphics *graphics = &subwindow->window->graphics;

	SDL_Rect src = {0, 0, graphics->tile_pixel_w, graphics->tile_pixel_h};

	int src_row = a & 0x7f;
	int src_col = c & 0x7f;

	src.x = src_col * src.w;
	src.y = src_row * src.h;

	if (graphics->overdraw_row != 0
			&& src_row >= graphics->overdraw_row
			&& src_row <= graphics->overdraw_max)
	{
		src.y -= src.h;
		dst.y -= dst.h;
		dst.h *= 2;
		src.h *= 2;
	}

	SDL_RenderCopy(subwindow->window->renderer,
			graphics->texture, &src, &dst);
}

static void render_tile_font_scaled(const struct subwindow *subwindow,
		int col, int row, int a, int c, bool fill, int dhrclip)
{
	struct graphics *graphics = &subwindow->window->graphics;

	SDL_Rect dst = {
		subwindow->inner_rect.x + col * subwindow->font_width,
		subwindow->inner_rect.y + row * subwindow->font_height,
		subwindow->font_width * tile_width,
		subwindow->font_height * tile_height
	};

	if (fill) {
		render_fill_rect(subwindow->window, subwindow->texture, &dst, &subwindow->color);
	}

	SDL_Rect src = {0, 0, graphics->tile_pixel_w, graphics->tile_pixel_h};

	SDL_SetRenderTarget(subwindow->window->renderer, subwindow->texture);

	int src_row = a & 0x7f;
	int src_col = c & 0x7f;

	src.x = src_col * src.w;
	src.y = src_row * src.h;

	if (graphics->overdraw_row != 0
			&& row > dhrclip
			&& src_row >= graphics->overdraw_row
			&& src_row <= graphics->overdraw_max)
	{
		src.y -= src.h;
		dst.y -= dst.h;
		dst.h *= 2;
		src.h *= 2;

		SDL_RenderCopy(subwindow->window->renderer,
				graphics->texture, &src, &dst);
	} else {
		SDL_RenderCopy(subwindow->window->renderer,
				graphics->texture, &src, &dst);
	}
}

static void render_grid_cell_tile(const struct subwindow *subwindow,
		SDL_Texture *texture, SDL_Rect tile, int x, int y)
{
	struct grid_data grid_data;
	int a;
	int ta;
	wchar_t c;
	wchar_t tc;

	map_info(loc(x, y), &grid_data);
	grid_data_as_text(&grid_data, &a, &c, &ta, &tc);

	SDL_SetRenderTarget(subwindow->window->renderer, texture);

	render_tile_rect_scaled(subwindow, x, y, tile, ta, tc);

	if (a == ta && c == tc) {
		return;
	}

	render_tile_rect_scaled(subwindow, x, y, tile, a, c);
}

static void clear_all_borders(struct sdlpui_window *window)
{
	for (size_t i = 0; i < N_ELEMENTS(window->subwindows); i++) {
		struct subwindow *subwindow = window->subwindows[i];
		if (subwindow != NULL) {
			subwindow->borders.error = false;
			render_borders(subwindow);
		}
	}
}

static void render_borders(struct subwindow *subwindow)
{
	SDL_Rect rect = {0};
	SDL_QueryTexture(subwindow->texture, NULL, NULL, &rect.w, &rect.h);

	SDL_Color *color;
	if (!subwindow->borders.error) {
		if (subwindow->borders.visible) {
			color = &subwindow->borders.color;
		} else {
			color = &subwindow->color;
		}
	} else {
		color = &subwindow->app->colors[DEFAULT_ERROR_COLOR];
	}

	render_outline_rect_width(subwindow->window,
			subwindow->texture, &rect, color,
			subwindow->borders.width);
}

static SDL_Texture *make_subwindow_texture(const struct sdlpui_window *window,
		int w, int h)
{
	SDL_Texture *texture = SDL_CreateTexture(window->renderer,
			window->pixelformat, SDL_TEXTUREACCESS_TARGET, w, h);
	if (texture == NULL) {
		quit_fmt("cannot create texture for subwindow in window %u: %s",
				window->index, SDL_GetError());
	}

	if (SDL_SetTextureBlendMode(texture, SDL_BLENDMODE_BLEND) != 0) {
		SDL_DestroyTexture(texture);
		quit_fmt("cannot set blend mode for texture in window %u: %s",
				window->index, SDL_GetError());
	}

	return texture;
}

static void get_minimum_subwindow_size(bool is_main, int cell_w, int cell_h,
		int *minw, int *minh)
{
	int min_cols, min_rows;

	if (is_main) {
		min_cols = MIN_COLS_MAIN;
		min_rows = MIN_ROWS_MAIN;
	} else {
		min_cols = MIN_COLS_OTHER;
		min_rows = MIN_ROWS_OTHER;
	}
	*minw = min_cols * cell_w + 2 * DEFAULT_BORDER;
	*minh = min_rows * cell_h + 2 * DEFAULT_BORDER;
}

static void get_minimum_window_size(struct sdlpui_window *window,
		int *minw, int *minh)
{
	int max_sub_w = 0, max_sub_h = 0;
	bool have_sub = false;
	int i;

	if (window->status_bar->ftb->query_minimum_size) {
		(*window->status_bar->ftb->query_minimum_size)(
			window->status_bar, window, minw, minh);
	} else {
		(*window->status_bar->ftb->query_natural_size)(
			window->status_bar, window, minw, minh);
	}

	for (i = 0; i < MAX_SUBWINDOWS; ++i) {
		if (window->subwindows[i]) {
			int this_min_w, this_min_h;

			get_minimum_subwindow_size(
				window->subwindows[i]->index == MAIN_SUBWINDOW,
				window->subwindows[i]->font->ttf.glyph.w,
				window->subwindows[i]->font->ttf.glyph.h,
				&this_min_w, &this_min_h);
			max_sub_w = MAX(max_sub_w, this_min_w);
			max_sub_h = MAX(max_sub_h, this_min_h);
			have_sub = true;
		}
	}

	if (!have_sub) {
		/*
		 * There's no currently configured subwindows; leave room
		 * for one.
		 */
		get_minimum_subwindow_size(false, window->app->def_font_w,
			window->app->def_font_h, &max_sub_w, &max_sub_h);
	}

	*minw = MAX(*minw, max_sub_w);
	*minh += max_sub_h;
}

/**
 * Return true if the given font (face and size) can be used for a subwindow.
 *
 * \param font is the font of interest.
 * \param subwindow is the subwindow of the interest.
 * \param sizing_rect will, if not NULL and the return value is true, be
 * dereferenced and the sizes set to the dimensions of the bounding rectangle
 * for the subwindow when using the given font.
 */
static bool is_usable_font_for_subwindow(const struct font *font,
		const struct subwindow *subwindow, SDL_Rect *sizing_rect)
{
	SDL_Rect bounds = subwindow->full_rect;

	if (!is_ok_col_row(subwindow, &bounds, font->ttf.glyph.w,
			font->ttf.glyph.h)) {
		get_minimum_subwindow_size(subwindow->index == MAIN_SUBWINDOW,
			font->ttf.glyph.w, font->ttf.glyph.h,
			&bounds.w, &bounds.h);
	}

	if (bounds.w > subwindow->window->inner_rect.w
			|| bounds.h > subwindow->window->inner_rect.h)
	{
		return false;
	}

	if (sizing_rect) {
		*sizing_rect = bounds;
	}
	return true;
}

/**
 * Calculate the range of font sizes that can be used for a subwindow.
 *
 * \param subwindow is the subwindow to use.
 * \param font is the font of interest.  If NULL, the current font for the
 * subwindow is used.
 * \param min_size is set to the minimum point size that can be used.  If
 * the font is not a vector font, this will be set to zero.
 * \param max_size is set to one past the maximum point size that can be used.
 * If no size works, *max_size will be the same as *min_size when the function
 * returns.  If the font is not a vector font and the subwindow can use the
 * font, *max_size will be one.
 */
static void calculate_subwindow_font_size_bounds(struct subwindow *subwindow,
		const struct font_info *font, int *min_size, int *max_size)
{
	struct font *trial_font;
	int lo, hi;

	if (!font) {
		assert(subwindow->font);
		font = &subwindow->app->fonts[subwindow->font->index];
	}

	if (font->type != FONT_TYPE_VECTOR) {
		*min_size = 0;
		trial_font = make_font(subwindow->window, font->name, 0);
		if (is_usable_font_for_subwindow(trial_font, subwindow, NULL)) {
			*max_size = 1;
		} else {
			*max_size = 0;
		}
		free_font(trial_font);
		return;
	}

	/* Find the smallest size that works. */
	lo = MIN_VECTOR_FONT_SIZE;
	while (1) {
		if (lo > MAX_VECTOR_FONT_SIZE) {
			/* No size works */
			*min_size = DEFAULT_VECTOR_FONT_SIZE;
			*max_size = DEFAULT_VECTOR_FONT_SIZE;
			return;
		}
		trial_font = make_font(subwindow->window, font->name, lo);
		if (is_usable_font_for_subwindow(trial_font, subwindow, NULL)) {
			free_font(trial_font);
			*min_size = lo;
			break;
		}
		free_font(trial_font);
		++lo;
	}

	/* Find the largest size that works using a binary search. */
	lo = *min_size;
	hi = MAX_VECTOR_FONT_SIZE + 1;
	while (1) {
		int try;

		if (lo == hi - 1) {
			*max_size = hi;
			return;
		}
		try = (lo + hi) / 2;
		trial_font = make_font(subwindow->window, font->name, try);
		if (is_usable_font_for_subwindow(trial_font, subwindow, NULL)) {
			lo = try;
		} else {
			hi = try;
		}
		free_font(trial_font);
	}
}

static bool handle_shortcut_editor_key(struct sdlpui_dialog *d,
		struct sdlpui_window *w, const struct SDL_KeyboardEvent *e)
{
	struct shortcut_editor_data *pse;
	keycode_t ch;
	uint8_t mods;

	SDL_assert(d->type_code == SHORTCUT_EDITOR_CODE && d->priv);
	pse = d->priv;
	if (pse->changing_shortcut == -1) {
		return sdlpui_dialog_handle_key(d, w, e);
	}
	keyboard_event_to_angband_key(e, w->app->kp_as_mod, &ch, &mods);
	if (ch) {
		char keypress_desc[40];

		SDL_assert(pse->changing_shortcut >= 0
			&& pse->changing_shortcut < MAX_WINDOWS);
		w->app->menu_shortcuts[pse->changing_shortcut].type = EVT_KBRD;
		w->app->menu_shortcuts[pse->changing_shortcut].code = ch;
		w->app->menu_shortcuts[pse->changing_shortcut].mods = mods;
		keypress_to_text(keypress_desc, sizeof(keypress_desc),
			&w->app->menu_shortcuts[pse->changing_shortcut], true);
		sdlpui_change_caption(
			&pse->shortcut_displays[pse->changing_shortcut],
			d, w, keypress_desc);
		pse->changing_shortcut = -1;
		sdlpui_change_caption(&pse->prompt_label, d, w, " ");
		return true;
	}
	return false;
}

static bool handle_shortcut_editor_textin(struct sdlpui_dialog *d,
		struct sdlpui_window *w, const struct SDL_TextInputEvent *e)
{
	struct shortcut_editor_data *pse;
	keycode_t ch;
	uint8_t mods;

	SDL_assert(d->type_code == SHORTCUT_EDITOR_CODE && d->priv);
	pse = d->priv;
	if (pse->changing_shortcut == -1) {
		return sdlpui_dialog_handle_textin(d, w, e);
	}
	textinput_event_to_angband_key(e, w->app->kp_as_mod, &ch, &mods);
	if (ch) {
		char keypress_desc[40];

		SDL_assert(pse->changing_shortcut >= 0
			&& pse->changing_shortcut < MAX_WINDOWS);
		w->app->menu_shortcuts[pse->changing_shortcut].type = EVT_KBRD;
		w->app->menu_shortcuts[pse->changing_shortcut].code = ch;
		w->app->menu_shortcuts[pse->changing_shortcut].mods = mods;
		keypress_to_text(keypress_desc, sizeof(keypress_desc),
			&w->app->menu_shortcuts[pse->changing_shortcut], true);
		sdlpui_change_caption(
			&pse->shortcut_displays[pse->changing_shortcut],
			d, w, keypress_desc);
		pse->changing_shortcut = -1;
		sdlpui_change_caption(&pse->prompt_label, d, w, " ");
		return true;
	}
	return false;
}

static void render_shortcut_editor(struct sdlpui_dialog *d,
		struct sdlpui_window *w)
{
	struct SDL_Renderer *r = sdlpui_get_renderer(w);
	SDL_Rect dst_r = d->rect;
	struct shortcut_editor_data *pse;
	const SDL_Color *color;
	int i;

	SDL_assert(d->type_code == SHORTCUT_EDITOR_CODE && d->priv);
	pse = d->priv;
	SDLPUI_RENDER_TRACER("shortcut editor", d, "(not extracted)", d->rect,
		d->rect, d->texture);

	SDL_SetRenderTarget(r, d->texture);
	color = sdlpui_get_color(w, SDLPUI_COLOR_DIALOG_BG);
	SDL_SetRenderDrawColor(r, color->r, color->g, color->b, color->a);
	if (d->texture) {
		dst_r.x = 0;
		dst_r.y = 0;
		SDL_RenderClear(r);
	} else {
		SDL_RenderFillRect(r, &dst_r);
	}
	for (i = 0; i < MAX_WINDOWS; ++i) {
		if (pse->labels[i].ftb->render) {
			(*pse->labels[i].ftb->render)(&pse->labels[i], d, w, r);
		}
		if (pse->shortcut_displays[i].ftb->render) {
			(*pse->shortcut_displays[i].ftb->render)(
				&pse->shortcut_displays[i], d, w, r);
		}
		if (pse->change_buttons[i].ftb->render) {
			(*pse->change_buttons[i].ftb->render)(
				&pse->change_buttons[i], d, w, r);
		}
		if (pse->clear_buttons[i].ftb->render) {
			(*pse->clear_buttons[i].ftb->render)(
				&pse->clear_buttons[i], d, w, r);
		}
	}
	if (pse->prompt_label.ftb->render) {
		(*pse->prompt_label.ftb->render)(&pse->prompt_label, d, w, r);
	}
	if (pse->close_button.ftb->render) {
		(*pse->close_button.ftb->render)(&pse->close_button, d, w, r);
	}
	if (pse->reset_button.ftb->render) {
		(*pse->reset_button.ftb->render)(&pse->reset_button, d, w, r);
	}
	d->dirty = false;
}

static void load_term(struct subwindow *subwindow)
{
	assert(!subwindow->linked);

	subwindow->term = mem_zalloc(sizeof(*subwindow->term));

	term_init(subwindow->term,
			subwindow->cols, subwindow->rows,
			SUBWINDOW_KEYQ_SIZE(subwindow));

	link_term(subwindow);

	term *old = Term;
	Term_activate(subwindow->term);
	Term_redraw();
	Term_activate(old);

	subwindow->linked = true;
	
	/* Initialize companion for subwindow 2 */
	if (subwindow->index == 2 && !subwindow->companion) {
		companion_init(subwindow);
	}
}

static void free_subwindow(struct subwindow *subwindow)
{
	assert(subwindow->loaded);

	/* Free companion data if it exists */
	if (subwindow->companion) {
		companion_free(subwindow->companion);
		subwindow->companion = NULL;
	}

	free_font(subwindow->font);
	subwindow->font = NULL;
	if (subwindow->texture != NULL) {
		SDL_DestroyTexture(subwindow->texture);
		subwindow->texture = NULL;
	}
	if (subwindow->aux_texture != NULL) {
		SDL_DestroyTexture(subwindow->aux_texture);
		subwindow->aux_texture = NULL;
	}
	if (subwindow->term != NULL) {
		unload_term(subwindow);
	}
	if (subwindow->config != NULL) {
		free_subwindow_config(subwindow->config);
		subwindow->config = NULL;
	}

	subwindow->window = NULL;
	subwindow->loaded = false;
	subwindow->inited = false;
}
